const { supabase } = require('../../supabaseClient');
const searchOrchestrator = require('./searchOrchestrator');
const { GoogleGenAI } = require('@google/genai');

const ai = new GoogleGenAI({
    apiKey: process.env.GEMINI_API_KEY,
    apiVersion: 'v1'
});

async function askGeminiJSON(prompt) {
    try {
        const response = await ai.models.generateContent({
            model: 'gemini-2.0-flash',
            contents: [{ role: 'user', parts: [{ text: prompt }] }],
            generationConfig: { responseMimeType: 'application/json', temperature: 0.2 }
        });
        const text = response.text().trim();
        // Strip code fences if any
        const clean = text.replace(/^```json\s*/i, '').replace(/^```\s*/i, '').replace(/\s*```$/i, '').trim();
        return JSON.parse(clean);
    } catch (e) {
        console.error('Gemini complementary JSON parse error:', e.message);
        return null;
    }
}

const COMPLEMENTARY_MAP = {
    'cutlery': ['utensils', 'dinnerware', 'cutting board'],
    'cookware': ['utensils', 'bakeware', 'apron'],
    'dinnerware': ['cutlery', 'glassware', 'tableware'],
    'glassware': ['dinnerware', 'bar tools', 'serveware'],
    'coffee & tea': ['mugs', 'teapot', 'spoons'],
    'utensils': ['cookware', 'cutting board', 'apron'],
    'bakeware': ['utensils', 'cookware', 'measuring tools'],
    'serveware': ['dinnerware', 'glassware', 'platters']
};

/**
 * Ask Gemini for complementary categories or product search terms.
 */
async function getComplementaryQueries(productName, productCategory) {
    const prompt = `
You are a premium e-commerce search and cross-sell recommendation engine.
Given the target product: "${productName}" in the category: "${productCategory}", identify exactly 2 complementary product types or categories that a customer would purchase to "use with" this product (e.g. cutting board for kitchen knives, mugs for espresso machines, teacups for a teapot).
Return ONLY a valid JSON array of 2 short search terms (1-3 words each). Example: ["cutting board", "knife sharpener"].
Do not include any explanation, code blocks, or backticks.
`;
    const res = await askGeminiJSON(prompt);
    if (Array.isArray(res) && res.length > 0) {
        return res;
    }
    
    // Advanced Heuristic fallback
    if (productCategory) {
        const catKey = productCategory.toLowerCase().trim();
        if (COMPLEMENTARY_MAP[catKey]) {
            return COMPLEMENTARY_MAP[catKey].slice(0, 2);
        }
    }
    return [`${productCategory} accessories`, 'kitchen utensils'];
}

/**
 * Orchestrate the suggested products feed:
 * 1. 2-3 Similar products (Strict same-category semantic search)
 * 2. 2-3 Complementary products (Cross-sell search queries generated by Gemini)
 * 3. 2-3 Personalized/Trending products
 */
async function getSuggestions(productId, deviceId) {
    try {
        // Fetch original product details
        const { data: product, error } = await supabase
            .from('products')
            .select('*')
            .eq('id', productId)
            .single();

        if (error || !product) {
            console.error("Failed to fetch product for suggestions:", error?.message);
            return [];
        }

        const seenIds = new Set();
        seenIds.add(productId);

        const similarList = [];
        const complementaryList = [];
        const personalizedList = [];

        // ── Tier 1: Similar Products (Strict Same Category) ─────────────────
        try {
            const hits = await searchOrchestrator.execute(product.name, deviceId, {
                category: product.category,
                limit: 6
            });
            for (const p of hits) {
                if (!seenIds.has(p.id)) {
                    similarList.push(p);
                    seenIds.add(p.id);
                    if (similarList.length >= 3) break;
                }
            }
        } catch (e) {
            console.error("Tier 1 suggestions failed:", e.message);
        }

        // ── Tier 2: Complementary Products (What it can be used with) ───────
        try {
            const queries = await getComplementaryQueries(product.name, product.category);
            for (const q of queries) {
                const hits = await searchOrchestrator.execute(q, deviceId, { limit: 4 });
                for (const p of hits) {
                    if (!seenIds.has(p.id) && p.category !== product.category) {
                        complementaryList.push(p);
                        seenIds.add(p.id);
                        if (complementaryList.length >= 3) break;
                    }
                }
                if (complementaryList.length >= 3) break;
            }
        } catch (e) {
            console.error("Tier 2 suggestions failed:", e.message);
        }

        // ── Tier 3: Personalized / Trending Products ────────────────────────
        try {
            const { data: popular } = await supabase
                .from('products')
                .select('*')
                .gt('stock', 0)
                .order('stock', { ascending: false })
                .limit(20);
            
            if (popular) {
                const personalizationEngine = require('./personalizationEngine');
                const boosted = await personalizationEngine.boost(popular, deviceId);
                for (const p of boosted) {
                    if (!seenIds.has(p.id)) {
                        personalizedList.push(p);
                        seenIds.add(p.id);
                        if (personalizedList.length >= 3) break;
                    }
                }
            }
        } catch (e) {
            console.error("Tier 3 suggestions failed:", e.message);
        }

        // Merge in the exact order requested: [Similar 2-3, Complementary 2-3, Personalized 2-3]
        const merged = [
            ...similarList.slice(0, 3),
            ...complementaryList.slice(0, 3),
            ...personalizedList.slice(0, 2)
        ];

        return merged.slice(0, 8);
    } catch (e) {
        console.error("Critical error in suggested products service:", e.message);
        return [];
    }
}

module.exports = { getSuggestions };
